{ name = "benchotron"
, dependencies =
  [ "arrays"
  , "datetime"
  , "effect"
  , "exceptions"
  , "exists"
  , "foldable-traversable"
  , "identity"
  , "integers"
  , "js-date"
  , "lcg"
  , "maybe"
  , "node-buffer"
  , "node-fs"
  , "node-readline"
  , "now"
  , "numbers"
  , "partial"
  , "prelude"
  , "profunctor"
  , "psci-support"
  , "quickcheck"
  , "strings"
  , "transformers"
  , "tuples"
  , "unfoldable"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
}
